server:
  port: 8081
#注册客户端配置
eureka:
  instance:
    #心跳间隔时间
    lease-renewal-interval-in-seconds: 10
    #告诉服务端多久未收到心跳则认为该服务关闭
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
  client:
    #定时刷新本地缓存
    #registry-fetch-interval-seconds: 5
    enabled: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: service-gateway
zuul:
  routes:
    api-order:
      path: /api-order/**
      serviceId: service-order
    api-user:
      path: /api-user/**
      serviceId: service-user