server:
  port: 8082
#注册客户端配置
eureka:
  instance:
    #心跳间隔时间
    lease-renewal-interval-in-seconds: 10
    #告诉服务端多久未收到心跳则认为该服务关闭
    lease-expiration-duration-in-seconds: 20
    #以IP地址注册到服务中心，相互注册使用IP地址
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    #定时刷新本地缓存
    registry-fetch-interval-seconds: 15
#    register-with-eureka: false
    enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8080/eureka/
spring:
  #应用信息
  application:
    name: service-monitor
  #集成spring-security拦截登录
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      notify:
        mail:
          #是谁发送
          from: 374649103@qq.com
          #发送给谁
          to: zengcheng_37@163.com
          #是否开启
          enabled: true
  #邮箱服务
  mail:
    #邮箱服务器
    host: smtp.qq.com
    #邮箱地址
    username: 374649103@qq.com
    #qq邮箱授权码，如果是其他邮箱一般为密码，具体看邮箱要求
    password: 'lvqawmpjwpbqbibf'
    properties:
      mail:
      smtp:
      # 设置是否需要认证，如果为true,那么用户名和密码就必须的，
      #如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
      auth: true
      starttls:
      #STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信
      #服务器需要tls验证
      enable: true
      required: true

