server:
  port: 8091
#注册客户端配置
eureka:
  instance:
    #心跳间隔时间
    lease-renewal-interval-in-seconds: 10
    #告诉服务端多久未收到心跳则认为该服务关闭
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
  client:
    #定时刷新本地缓存
    #registry-fetch-interval-seconds: 5
    enabled: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
spring:
  #应用信息
  application:
    name: service-user
  # 异常处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  #redis 连接配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 5000ms  # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-wait:   1ms   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle:   8   # 连接池中的最大空闲连接
        min-idle:   0   # 连接池中的最小空闲连接

  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: yzzy65203
#开启Hystrix断路器
feign:
  hystrix:
    enabled: true
